const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const money=n=>`${new Intl.NumberFormat("th-TH",{maximumFractionDigits:0}).format(n||0)} บาท`;const labels={PAID:"ชำระแล้ว",PENDING:"รอตรวจสอบ",UNPAID:"ยังไม่ชำระ",MISSING:"ยังไม่ส่งข้อมูล"};let tableCount=1,schools=[],publicRows=[],adminRows=[],token=sessionStorage.getItem("adminToken");
function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(el.timer);el.timer=setTimeout(()=>el.classList.remove("show"),2400)}
function setButtonLoading(button,loading,label="กำลังโหลด…"){if(!button)return;if(loading){if(!button.dataset.originalHtml)button.dataset.originalHtml=button.innerHTML;button.disabled=true;button.setAttribute("aria-busy","true");button.innerHTML=`<span class="button-spinner" aria-hidden="true"></span><span>${label}</span>`}else{button.disabled=false;button.removeAttribute("aria-busy");if(button.dataset.originalHtml){button.innerHTML=button.dataset.originalHtml;delete button.dataset.originalHtml}}}
function loadingPanel(label="กำลังโหลดข้อมูล…"){return`<div class="loading-panel" role="status"><span class="button-spinner" aria-hidden="true"></span><span>${label}</span></div>`}
function route(){const name=location.hash.slice(1)||"survey";$$('[data-view]').forEach(v=>v.hidden=v.dataset.view!==name);$$('[data-route-link]').forEach(a=>a.classList.toggle("active",a.dataset.routeLink===name));if(name==="status")loadStatus();if(name==="admin")showAdmin()}window.addEventListener("hashchange",route);
async function init(){const select=$("#school");select.disabled=true;try{schools=await API.call("getSchools");select.innerHTML='<option value="">เลือกโรงเรียนของท่าน</option>'+schools.map(s=>`<option value="${s.schoolId}">${s.schoolName}</option>`).join("")}catch(e){select.innerHTML='<option value="">ไม่สามารถโหลดรายชื่อได้</option>';toast(e.message)}finally{select.disabled=false}route()}
function updateCount(delta=0){tableCount=Math.min(APP_CONFIG.MAX_TABLES,Math.max(1,tableCount+delta));$("#tableCount").textContent=tableCount;$("#summaryTables").textContent=`${tableCount} โต๊ะ`;$("#totalAmount").textContent=money(tableCount*APP_CONFIG.TABLE_PRICE)}
$("#minus").onclick=()=>updateCount(-1);$("#plus").onclick=()=>updateCount(1);$$('input[name="payment"]').forEach(x=>x.onchange=()=>{const transfer=x.value==="transfer"&&x.checked;$("#transferSection").hidden=!transfer;$("#slipInput").required=transfer;if(!transfer){$("#slipInput").value="";$("#slipPreview").hidden=true}});$("#copyAccount").onclick=async e=>{const btn=e.currentTarget;setButtonLoading(btn,true,"กำลังคัดลอก…");try{await navigator.clipboard.writeText("6653336433");toast("คัดลอกเลขบัญชีแล้ว")}catch(err){toast("ไม่สามารถคัดลอกได้")}finally{setButtonLoading(btn,false)}};$("#slipInput").onchange=e=>{const f=e.target.files[0];if(!f)return;if(!["image/jpeg","image/png","image/webp"].includes(f.type)||f.size>APP_CONFIG.MAX_FILE_SIZE){e.target.value="";$("#slipError").textContent="กรุณาเลือกไฟล์ภาพ JPG, PNG หรือ WEBP ขนาดไม่เกิน 5 MB";return}$("#slipError").textContent="";$("#slipPreview").src=URL.createObjectURL(f);$("#slipPreview").hidden=false};
function fileData(file){return new Promise((resolve,reject)=>{if(!file)return resolve(null);const r=new FileReader();r.onload=()=>resolve({name:file.name,type:file.type,data:String(r.result).split(",")[1]});r.onerror=reject;r.readAsDataURL(file)})}
let pendingSubmission=null;
$("#surveyForm").onsubmit=e=>{e.preventDefault();const payment=$("input[name=payment]:checked")?.value,phone=$("#phone").value.replace(/\D/g,"");let error="";if(!$("#school").value)error="กรุณาเลือกโรงเรียน";else if(!$("#contactName").value.trim())error="กรุณากรอกชื่อผู้ติดต่อ";else if(!/^0\d{8,9}$/.test(phone))error="กรุณากรอกเบอร์โทรศัพท์ให้ถูกต้อง";else if(!payment)error="กรุณาเลือกวิธีชำระเงิน";else if(payment==="transfer"&&!$("#slipInput").files[0])error="กรุณาแนบสลิปโอนเงิน";else if(!$("#consent").checked)error="กรุณายืนยันความถูกต้องของข้อมูล";if(error)return toast(error);const school=schools.find(s=>s.schoolId===$("#school").value),file=$("#slipInput").files[0];pendingSubmission={schoolId:school.schoolId,schoolName:school.schoolName,numberOfTables:tableCount,contactName:$("#contactName").value.trim(),phone,paymentMethod:payment,file};$("#confirmContent").innerHTML=`<div class="confirm-item wide"><small>โรงเรียน</small><strong>${school.schoolName}</strong></div><div class="confirm-item"><small>จำนวนโต๊ะ</small><strong>${tableCount} โต๊ะ (${tableCount*8} ที่นั่ง)</strong></div><div class="confirm-item"><small>ยอดที่ต้องชำระ</small><strong>${money(tableCount*APP_CONFIG.TABLE_PRICE)}</strong></div><div class="confirm-item"><small>ผู้ติดต่อ</small><strong>${pendingSubmission.contactName}</strong></div><div class="confirm-item"><small>เบอร์โทรศัพท์</small><strong>${phone}</strong></div><div class="confirm-item wide"><small>วิธีชำระเงิน</small><strong>${payment==="transfer"?`โอนเงิน · แนบสลิปแล้ว (${file.name})`:"เงินสด · ชำระกับผู้ประสานงาน"}</strong></div>`;$("#confirmDialog").showModal()};
$("#editSubmission").onclick=()=>{$("#confirmDialog").close();pendingSubmission=null};
$("#confirmSubmission").onclick=async()=>{if(!pendingSubmission)return;const btn=$("#confirmSubmission"),form=$("#surveyForm");setButtonLoading(btn,true,"กำลังส่งข้อมูล…");try{const p=pendingSubmission,result=await API.call("submitResponse",{schoolId:p.schoolId,numberOfTables:p.numberOfTables,contactName:p.contactName,phone:p.phone,paymentMethod:p.paymentMethod,slip:await fileData(p.file)});$("#confirmDialog").close();$("#successSchool").textContent=result.schoolName;$("#receiptId").textContent=result.id;$("#successDialog").showModal();form.reset();pendingSubmission=null;tableCount=1;updateCount();$("#transferSection").hidden=true;$("#slipPreview").hidden=true}catch(err){toast(err.message)}finally{setButtonLoading(btn,false)}};
function statCards(rows,admin=false){const submitted=rows.filter(x=>x.paymentStatus!=="MISSING"),tables=submitted.reduce((s,x)=>s+(+x.numberOfTables||0),0),total=submitted.reduce((s,x)=>s+(+x.amount||0),0),paid=submitted.filter(x=>x.paymentStatus==="PAID").reduce((s,x)=>s+(+x.amount||0),0);return[{l:"โรงเรียนตอบแล้ว",v:`${submitted.length} / ${rows.length}`,s:"แห่ง"},{l:"จำนวนโต๊ะทั้งหมด",v:tables,s:"โต๊ะ"},{l:admin?"ยอดที่ยืนยันแล้ว":"ยอดรวมทั้งหมด",v:money(admin?paid:total),s:""},{l:admin?"ยอดคงค้าง":"ชำระแล้ว",v:money(admin?total-paid:paid),s:""}].map(x=>`<div class="stat"><span>${x.l}</span><strong>${x.v}</strong><small>${x.s}</small></div>`).join("")}
function rowHtml(x,admin=false){return`<tr><td><strong>${x.schoolName}</strong>${admin&&x.contactName?`<small>${x.contactName} · ${x.phone}</small>`:""}</td><td>${x.numberOfTables||"—"}</td><td>${x.amount?money(x.amount):"—"}</td><td>${x.paymentMethod==="transfer"?"โอนเงิน":x.paymentMethod==="cash"?"เงินสด":"—"}</td><td><span class="status-pill status-${x.paymentStatus}">${labels[x.paymentStatus]}</span></td>${admin?`<td><button class="action-button" data-detail="${x.id||""}" ${!x.id?"disabled":""}>จัดการ</button></td>`:""}</tr>`}
async function loadStatus(){$("#publicStats").innerHTML=loadingPanel("กำลังโหลดสถานะ…");$("#publicTable").innerHTML='<tr><td colspan="5">กำลังโหลดข้อมูล…</td></tr>';try{publicRows=await API.call("getPublicStatus");renderPublic();$("#lastUpdated").textContent=new Intl.DateTimeFormat("th-TH",{dateStyle:"medium",timeStyle:"short"}).format(new Date())}catch(e){$("#publicStats").innerHTML="";$("#publicTable").innerHTML='<tr><td colspan="5">ไม่สามารถโหลดข้อมูลได้</td></tr>';toast(e.message)}}function renderPublic(){const q=$("#publicSearch").value.toLowerCase();$("#publicStats").innerHTML=statCards(publicRows);$("#publicTable").innerHTML=publicRows.filter(x=>x.schoolName.toLowerCase().includes(q)).map(x=>rowHtml(x)).join("")}$("#publicSearch").oninput=renderPublic;
async function showAdmin(){if(!token){$("#loginPanel").hidden=false;$("#dashboard").hidden=true;return}$("#loginPanel").hidden=true;$("#dashboard").hidden=false;$("#adminStats").innerHTML=loadingPanel("กำลังโหลดแดชบอร์ด…");$("#adminTable").innerHTML='<tr><td colspan="6">กำลังโหลดข้อมูล…</td></tr>';try{adminRows=await API.call("getAdminData",{token});renderAdmin()}catch(e){token=null;sessionStorage.removeItem("adminToken");showAdmin();toast("เซสชันหมดอายุ กรุณาเข้าสู่ระบบใหม่")}}
$("#loginForm").onsubmit=async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button[type="submit"]');$("#loginError").textContent="";setButtonLoading(btn,true,"กำลังเข้าสู่ระบบ…");try{const r=await API.call("adminLogin",{password:$("#adminPassword").value});token=r.token;sessionStorage.setItem("adminToken",token);await showAdmin()}catch(err){$("#loginError").textContent=err.message}finally{setButtonLoading(btn,false)}};$("#togglePassword").onclick=()=>{const i=$("#adminPassword"),show=i.type==="password";i.type=show?"text":"password";$("#togglePassword").textContent=show?"ซ่อน":"แสดง"};$("#logoutButton").onclick=async e=>{const btn=e.currentTarget;setButtonLoading(btn,true,"กำลังออก…");try{await API.call("adminLogout",{token});token=null;sessionStorage.removeItem("adminToken");showAdmin()}catch(err){toast(err.message)}finally{setButtonLoading(btn,false)}};
function renderAdmin(){const q=$("#adminSearch").value.toLowerCase(),f=$("#statusFilter").value;$("#adminStats").innerHTML=statCards(adminRows,true);$("#adminTable").innerHTML=adminRows.filter(x=>(f==="ALL"||x.paymentStatus===f)&&(`${x.schoolName} ${x.contactName||""}`).toLowerCase().includes(q)).map(x=>rowHtml(x,true)).join("");$$('[data-detail]').forEach(b=>b.onclick=()=>openDetail(b.dataset.detail))}$("#adminSearch").oninput=renderAdmin;$("#statusFilter").onchange=renderAdmin;
function openDetail(id){const x=adminRows.find(v=>v.id===id);$("#detailContent").innerHTML=`<span class="eyebrow">รายละเอียดรายการ</span><h2>${x.schoolName}</h2><div class="detail-grid"><div><small>ผู้ติดต่อ</small><b>${x.contactName}</b></div><div><small>โทรศัพท์</small><b>${x.phone}</b></div><div><small>จำนวนโต๊ะ</small><b>${x.numberOfTables} โต๊ะ</b></div><div><small>ยอดชำระ</small><b>${money(x.amount)}</b></div><div><small>วิธีชำระ</small><b>${x.paymentMethod==="transfer"?"โอนเงิน":"เงินสด"}</b></div><div><small>สถานะ</small><b>${labels[x.paymentStatus]}</b></div></div><div class="status-actions"><button class="paid" data-status="PAID">✓ ชำระแล้ว</button><button class="pending" data-status="PENDING">รอตรวจสอบ</button><button class="unpaid" data-status="UNPAID">ยังไม่ชำระ</button></div>`;$$('[data-status]').forEach(b=>b.onclick=async()=>{const buttons=$$('[data-status]');buttons.forEach(x=>x.disabled=true);setButtonLoading(b,true,"กำลังบันทึก…");try{await API.call("updatePaymentStatus",{token,id,status:b.dataset.status});$("#detailDialog").close();await showAdmin();toast("อัปเดตสถานะแล้ว")}catch(err){toast(err.message);buttons.forEach(x=>x.disabled=false);setButtonLoading(b,false)}});$("#detailDialog").showModal()}
$$('.dialog-close').forEach(b=>b.onclick=()=>b.closest("dialog").close());
const viewStatusButton=$("#successDialog a[href='#status']");
if(viewStatusButton)viewStatusButton.addEventListener("click",()=>$("#successDialog").close());
init();
